version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rtsp-detection-backend
    volumes:
      - detection_results:/app/detection_results
    environment:
      - RESULTS_DIR=/app/detection_results
    ports:
      - "5000:5000"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rtsp-detection-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  detection_results:
