version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rtsp-detection-backend
    volumes:
      - detection_results:/app/detection_results
      - ./saved_images:/app/saved_images
    environment:
      - RESULTS_DIR=/app/detection_results
      - IMAGES_DIR=/app/saved_images
      - DEVICE=cpu
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - rtsp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rtsp-detection-frontend
    environment:
      # Utiliser le nom du service backend au lieu de localhost
      - REACT_APP_API_URL=http://backend:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rtsp-network

volumes:
  detection_results:

# Ajouter un réseau dédié
networks:
  rtsp-network:
    driver: bridge
