version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: rtsp-detection-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - rtsp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rtsp-detection-backend
    volumes:
      - detection_results:/app/detection_results
      - ./saved_images:/app/saved_images
    environment:
      - RESULTS_DIR=/app/detection_results
      - IMAGES_DIR=/app/saved_images
      - DEVICE=cpu
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - rtsp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rtsp-detection-frontend
    environment:
      - REACT_APP_API_URL=/api
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rtsp-network

volumes:
  detection_results:

networks:
  rtsp-network:
    driver: bridge
